# Random matrix generator 

Input: integer numbers n and m, string fileName

Output: matrix mx(n+1) of random integer numbers written in file with name fileName (in folder tests)

In [3]:
import numpy as np
import random

In [4]:
def generate(m, n):
    return np.random.randint(low=-5000, high=5000, size=(m, n+1))

In [62]:
def saveToFile(matrix, path):
    mat = np.matrix(matrix)
    print("Saving followinf matrix into " + path + "...")
    print(mat)
    with open(path+".txt",'wb') as f:
        for line in mat:
            np.savetxt(f, line, fmt='%s')

In [64]:
print("Enter m")
m = int(input())

print("Enter n")
n = int(input()) 

Enter m
50
Enter n
50


In [65]:
matrix = generate(m, n)

In [66]:
print("Enter file name")
fileName = input()

Enter file name
test1


In [67]:
saveToFile(matrix, "tests/" + fileName)

Saving followinf matrix into tests/test1...
[[-3938   397  4520 ... -3035  4190  2470]
 [ 3033  -271  1126 ... -2253  2542  1263]
 [ -765 -4520  3928 ... -3620 -2039   814]
 ...
 [ 4206  3568 -3220 ... -1854 -4991 -2996]
 [-2186  3381 -4049 ...  2477  4468 -4189]
 [-1758 -3441  4207 ... -1391   208   157]]
