# Random matrix generator 

Input: integer numbers n and m, string fileName

Output: matrix mx(n+1) of random integer numbers written in file with name fileName (in folder tests)

In [1]:
import numpy as np
import random

In [2]:
def generate(m, n):
    return np.random.randint(low=-5000, high=5000, size=(m, n+1))

In [3]:
def saveToFile(matrix, path):
    mat = np.matrix(matrix)
    print("Saving following matrix into: " + path + ".txt...\n")
    print(mat)
    with open(path+".txt",'wb') as f:
        for line in mat:
            np.savetxt(f, line, fmt='%s')

In [17]:
print("Enter m")
m = int(input())

print("Enter n")
n = int(input()) 

Enter m
200
Enter n
3


In [18]:
matrix = generate(m, n)

In [19]:
print("Enter file name")
fileName = input()

Enter file name
200x5


In [20]:
# saveToFile(matrix, "tests/" + fileName)
saveToFile(matrix, "bigTests/" + fileName)

Saving following matrix into: tests/200x5.txt...

[[  -13  2411 -1833 -3491]
 [ 1636  2169  -498  2321]
 [ 2712 -2460 -4610 -2882]
 [ 4870 -4011 -3249  -651]
 [  157  3731  -866  1685]
 [-2258  1454 -2003 -4082]
 [ 3476 -3873    81 -4120]
 [  984 -2274  -598 -1816]
 [ 4161 -2380  2509 -1124]
 [-2313 -3183    94  1994]
 [ -376 -2327  4321  4149]
 [-4201   352 -3696   979]
 [ 4343  3081   987  2060]
 [-3987  2928 -1461  2866]
 [ 2766  1096  3785  1615]
 [ -539  2992   962 -3046]
 [ 1353  3662  4621  2297]
 [ 3764   836  -754 -4417]
 [-3735   -44   238  2906]
 [ 3066  4196 -4393 -1048]
 [ 4562 -1924  -648 -3952]
 [  109  1286 -3144 -4543]
 [  -32    48   687  2034]
 [ 4123  -517  1932 -2937]
 [  553   325  4154  2001]
 [ 2873 -3704  1042   596]
 [-4513 -3107  4130   498]
 [ 4093  3352   830  1629]
 [ 4446  4903  1051 -4316]
 [ -195   423 -1956  4036]
 [  407 -3110  2386  2562]
 [-4831 -1356  3442 -1066]
 [-4260  -487 -3554 -4304]
 [  790  1201 -1201  4931]
 [-2443 -2342  3629  4803]
 [ 11