# Random matrix generator 

Input: integer numbers n and m, string fileName

Output: matrix mx(n+1) of random integer numbers written in file with name fileName (in folder tests)

In [1]:
import numpy as np
import random

In [2]:
def generate(m, n):
    return np.random.randint(low=-5000, high=5000, size=(m, n+1))

In [3]:
def saveToFile(matrix, path):
    mat = np.matrix(matrix)
    print("Saving following matrix into: " + path + ".txt...\n")
    print(mat)
    with open(path+".txt",'wb') as f:
        for line in mat:
            np.savetxt(f, line, fmt='%s')

In [4]:
print("Enter m")
m = int(input())

print("Enter n")
n = int(input()) 

Enter m
35
Enter n
4


In [5]:
matrix = generate(m, n)

In [6]:
print("Enter file name")
fileName = input()

Enter file name
35x4


In [7]:
saveToFile(matrix, "tests/" + fileName)

Saving following matrix into: tests/35x4.txt...

[[ 1104  4981 -1023 -4621 -4919]
 [-1419 -1874  1429   893  4896]
 [ 2820 -3642  -249    65  2326]
 [ 3803   -71 -1703  3687  1712]
 [-1991 -4801 -2647 -1859  -641]
 [-3452 -3631    17 -1682  2262]
 [-3908 -3960  3775  -868  2812]
 [ 1045  1705 -2778    94 -2969]
 [ 2383 -3214  4392   694 -2978]
 [ 4347 -1130  3399 -3906  3212]
 [-2110  -640  4408  2626    69]
 [-2616  4697 -2992  3538  4623]
 [  752 -2597  1198  2640   -98]
 [ 3588  3699  2585  1769 -3250]
 [  140 -4225  4522  3451 -2371]
 [  589  -865  2988 -4718 -4115]
 [-3373  3640 -2349   887  2924]
 [-4282   108  3233 -3612 -4907]
 [-1275  1233  -337  3047  4425]
 [ 2529 -2677 -4007 -2498  4402]
 [-4847 -3021  -360  4015  4678]
 [-1346  1715 -1190  3393 -1097]
 [  521  2108  1579  3314   765]
 [-1036  1079 -1012  2237   272]
 [ 2306 -4871 -1099  3242  1060]
 [-1667  2413  3707 -4077  4973]
 [ 1107   111 -3480 -3980 -1792]
 [ 2585 -3194  4822 -1194 -1055]
 [-2477  4200  1979  3795 -